[database]
database = 'servling'
host = 'localhost'
password = 'servling'
port = 5432
username = 'servling'

[security]
[security.token]
access_token_duration = '15m'
access_token_secret_key = 'JZfq6BQVJ59lVY/bZJvV+ZcqQxFMj0M6oJEufgFGQUE='
refresh_token_duration = '24h'
refresh_token_private_key = 'AQD0lRquudPeXxy4mpjIKJuZisFGv+//egcaqnrgidmrxCqqccJwgJrBKZnilqa5dABEQ0ZxjufWW8Glsgv72w=='
refresh_token_public_key = 'q8QqqnHCcICawSmZ4pamuXQARENGcY7n1lvBpbIL+9s='

[server]
host = 'localhost'
port = 8080
