// Code generated by ent, DO NOT EDIT.

package ingress

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/servling/servling/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Ingress {
	return predicate.Ingress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Ingress {
	return predicate.Ingress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Ingress {
	return predicate.Ingress(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldEQ(FieldName, v))
}

// TargetPort applies equality check predicate on the "target_port" field. It's identical to TargetPortEQ.
func TargetPort(v uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldEQ(FieldTargetPort, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Ingress {
	return predicate.Ingress(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Ingress {
	return predicate.Ingress(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Ingress {
	return predicate.Ingress(sql.FieldContainsFold(FieldName, v))
}

// TargetPortEQ applies the EQ predicate on the "target_port" field.
func TargetPortEQ(v uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldEQ(FieldTargetPort, v))
}

// TargetPortNEQ applies the NEQ predicate on the "target_port" field.
func TargetPortNEQ(v uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldNEQ(FieldTargetPort, v))
}

// TargetPortIn applies the In predicate on the "target_port" field.
func TargetPortIn(vs ...uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldIn(FieldTargetPort, vs...))
}

// TargetPortNotIn applies the NotIn predicate on the "target_port" field.
func TargetPortNotIn(vs ...uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldNotIn(FieldTargetPort, vs...))
}

// TargetPortGT applies the GT predicate on the "target_port" field.
func TargetPortGT(v uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldGT(FieldTargetPort, v))
}

// TargetPortGTE applies the GTE predicate on the "target_port" field.
func TargetPortGTE(v uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldGTE(FieldTargetPort, v))
}

// TargetPortLT applies the LT predicate on the "target_port" field.
func TargetPortLT(v uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldLT(FieldTargetPort, v))
}

// TargetPortLTE applies the LTE predicate on the "target_port" field.
func TargetPortLTE(v uint16) predicate.Ingress {
	return predicate.Ingress(sql.FieldLTE(FieldTargetPort, v))
}

// HasDomain applies the HasEdge predicate on the "domain" edge.
func HasDomain() predicate.Ingress {
	return predicate.Ingress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DomainTable, DomainColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomainWith applies the HasEdge predicate on the "domain" edge with a given conditions (other predicates).
func HasDomainWith(preds ...predicate.Domain) predicate.Ingress {
	return predicate.Ingress(func(s *sql.Selector) {
		step := newDomainStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasService applies the HasEdge predicate on the "service" edge.
func HasService() predicate.Ingress {
	return predicate.Ingress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServiceTable, ServiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServiceWith applies the HasEdge predicate on the "service" edge with a given conditions (other predicates).
func HasServiceWith(preds ...predicate.Service) predicate.Ingress {
	return predicate.Ingress(func(s *sql.Selector) {
		step := newServiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ingress) predicate.Ingress {
	return predicate.Ingress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ingress) predicate.Ingress {
	return predicate.Ingress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ingress) predicate.Ingress {
	return predicate.Ingress(sql.NotPredicates(p))
}
