// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApplicationsColumns holds the columns for the "applications" table.
	ApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "stopped"},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "template_applications", Type: field.TypeString, Nullable: true},
	}
	// ApplicationsTable holds the schema information for the "applications" table.
	ApplicationsTable = &schema.Table{
		Name:       "applications",
		Columns:    ApplicationsColumns,
		PrimaryKey: []*schema.Column{ApplicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "applications_templates_applications",
				Columns:    []*schema.Column{ApplicationsColumns[8]},
				RefColumns: []*schema.Column{TemplatesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DomainsColumns holds the columns for the "domains" table.
	DomainsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "certificate", Type: field.TypeString, Nullable: true},
		{Name: "key", Type: field.TypeString, Nullable: true},
		{Name: "cloudflare_email", Type: field.TypeString, Nullable: true},
		{Name: "cloudflare_api_key", Type: field.TypeString, Nullable: true},
	}
	// DomainsTable holds the schema information for the "domains" table.
	DomainsTable = &schema.Table{
		Name:       "domains",
		Columns:    DomainsColumns,
		PrimaryKey: []*schema.Column{DomainsColumns[0]},
	}
	// IngressesColumns holds the columns for the "ingresses" table.
	IngressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "target_port", Type: field.TypeUint16},
		{Name: "domain_ingresses", Type: field.TypeString, Nullable: true},
		{Name: "service_ingresses", Type: field.TypeString, Nullable: true},
	}
	// IngressesTable holds the schema information for the "ingresses" table.
	IngressesTable = &schema.Table{
		Name:       "ingresses",
		Columns:    IngressesColumns,
		PrimaryKey: []*schema.Column{IngressesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ingresses_domains_ingresses",
				Columns:    []*schema.Column{IngressesColumns[3]},
				RefColumns: []*schema.Column{DomainsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "ingresses_services_ingresses",
				Columns:    []*schema.Column{IngressesColumns[4]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ServicesColumns holds the columns for the "services" table.
	ServicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "service_name", Type: field.TypeString, Unique: true},
		{Name: "image", Type: field.TypeString},
		{Name: "ports", Type: field.TypeJSON, Nullable: true},
		{Name: "environment", Type: field.TypeJSON, Nullable: true},
		{Name: "entrypoint", Type: field.TypeString, Nullable: true},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "stopped"},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "application_services", Type: field.TypeString, Nullable: true},
	}
	// ServicesTable holds the schema information for the "services" table.
	ServicesTable = &schema.Table{
		Name:       "services",
		Columns:    ServicesColumns,
		PrimaryKey: []*schema.Column{ServicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "services_applications_services",
				Columns:    []*schema.Column{ServicesColumns[12]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TemplatesColumns holds the columns for the "templates" table.
	TemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TemplatesTable holds the schema information for the "templates" table.
	TemplatesTable = &schema.Table{
		Name:       "templates",
		Columns:    TemplatesColumns,
		PrimaryKey: []*schema.Column{TemplatesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "token_version", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApplicationsTable,
		DomainsTable,
		IngressesTable,
		ServicesTable,
		TemplatesTable,
		UsersTable,
	}
)

func init() {
	ApplicationsTable.ForeignKeys[0].RefTable = TemplatesTable
	IngressesTable.ForeignKeys[0].RefTable = DomainsTable
	IngressesTable.ForeignKeys[1].RefTable = ServicesTable
	ServicesTable.ForeignKeys[0].RefTable = ApplicationsTable
}
