// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// Domain is the predicate function for domain builders.
type Domain func(*sql.Selector)

// Ingress is the predicate function for ingress builders.
type Ingress func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
